// irregularVerbs.js
const irregularVerbs = [
  { base: "be", past: "was / were", pastParticiple: "been", meaning: "menjadi / berada" },
  { base: "begin", past: "began", pastParticiple: "begun", meaning: "memulai" },
  { base: "break", past: "broke", pastParticiple: "broken", meaning: "memecahkan" },
  { base: "bring", past: "brought", pastParticiple: "brought", meaning: "membawa" },
  { base: "build", past: "built", pastParticiple: "built", meaning: "membangun" },
  { base: "buy", past: "bought", pastParticiple: "bought", meaning: "membeli" },
  { base: "catch", past: "caught", pastParticiple: "caught", meaning: "menangkap" },
  { base: "choose", past: "chose", pastParticiple: "chosen", meaning: "memilih" },
  { base: "come", past: "came", pastParticiple: "come", meaning: "datang" },
  { base: "cost", past: "cost", pastParticiple: "cost", meaning: "berharga" },
  { base: "cut", past: "cut", pastParticiple: "cut", meaning: "memotong" },
  { base: "do", past: "did", pastParticiple: "done", meaning: "melakukan" },
  { base: "draw", past: "drew", pastParticiple: "drawn", meaning: "menggambar" },
  { base: "drink", past: "drank", pastParticiple: "drunk", meaning: "minum" },
  { base: "drive", past: "drove", pastParticiple: "driven", meaning: "mengemudi" },
  { base: "eat", past: "ate", pastParticiple: "eaten", meaning: "makan" },
  { base: "fall", past: "fell", pastParticiple: "fallen", meaning: "jatuh" },
  { base: "feel", past: "felt", pastParticiple: "felt", meaning: "merasakan" },
  { base: "find", past: "found", pastParticiple: "found", meaning: "menemukan" },
  { base: "fly", past: "flew", pastParticiple: "flown", meaning: "terbang" },
  { base: "forget", past: "forgot", pastParticiple: "forgotten", meaning: "melupakan" },
  { base: "get", past: "got", pastParticiple: "gotten / got", meaning: "mendapatkan" },
  { base: "give", past: "gave", pastParticiple: "given", meaning: "memberi" },
  { base: "go", past: "went", pastParticiple: "gone", meaning: "pergi" },
  { base: "grow", past: "grew", pastParticiple: "grown", meaning: "tumbuh" },
  { base: "have", past: "had", pastParticiple: "had", meaning: "memiliki" },
  { base: "hear", past: "heard", pastParticiple: "heard", meaning: "mendengar" },
  { base: "hide", past: "hid", pastParticiple: "hidden", meaning: "menyembunyikan" },
  { base: "hold", past: "held", pastParticiple: "held", meaning: "memegang" },
  { base: "keep", past: "kept", pastParticiple: "kept", meaning: "menyimpan" },
  { base: "know", past: "knew", pastParticiple: "known", meaning: "mengetahui" },
  { base: "leave", past: "left", pastParticiple: "left", meaning: "meninggalkan" },
  { base: "lose", past: "lost", pastParticiple: "lost", meaning: "kehilangan" },
  { base: "make", past: "made", pastParticiple: "made", meaning: "membuat" },
  { base: "meet", past: "met", pastParticiple: "met", meaning: "bertemu" },
  { base: "pay", past: "paid", pastParticiple: "paid", meaning: "membayar" },
  { base: "put", past: "put", pastParticiple: "put", meaning: "meletakkan" },
  { base: "read", past: "read", pastParticiple: "read", meaning: "membaca" },
  { base: "ride", past: "rode", pastParticiple: "ridden", meaning: "mengendarai" },
  { base: "run", past: "ran", pastParticiple: "run", meaning: "berlari" },
  { base: "say", past: "said", pastParticiple: "said", meaning: "mengatakan" },
  { base: "see", past: "saw", pastParticiple: "seen", meaning: "melihat" },
  { base: "sell", past: "sold", pastParticiple: "sold", meaning: "menjual" },
  { base: "send", past: "sent", pastParticiple: "sent", meaning: "mengirim" },
  { base: "sit", past: "sat", pastParticiple: "sat", meaning: "duduk" },
  { base: "sleep", past: "slept", pastParticiple: "slept", meaning: "tidur" },
  { base: "speak", past: "spoke", pastParticiple: "spoken", meaning: "berbicara" },
  { base: "stand", past: "stood", pastParticiple: "stood", meaning: "berdiri" },
  { base: "take", past: "took", pastParticiple: "taken", meaning: "mengambil" },
  { base: "teach", past: "taught", pastParticiple: "taught", meaning: "mengajar" },
  { base: "tell", past: "told", pastParticiple: "told", meaning: "memberitahu" },
  { base: "think", past: "thought", pastParticiple: "thought", meaning: "berpikir" },
  { base: "throw", past: "threw", pastParticiple: "thrown", meaning: "melempar" },
  { base: "understand", past: "understood", pastParticiple: "understood", meaning: "memahami" },
  { base: "wear", past: "wore", pastParticiple: "worn", meaning: "memakai" },
  { base: "win", past: "won", pastParticiple: "won", meaning: "menang" },
  { base: "write", past: "wrote", pastParticiple: "written", meaning: "menulis" }
];

